### ISSUE TITLE
Doesn't work without watchdog chip MAX693

### ISSUE THREAD

**Issue by xrayer** [skiselev/easy_z80#4]
Hi,
I just finished my Easy Z80 board except I don't have MAX693 that is quite expansive and I don't need it. I flashed easy_z80_no_wdog.jed to PLD so I assume it's intended to run also without watchdog. But the board was dead. After some scoping around bus signals I see that data signals was quite messy and CS# signal of RAM was on unacceptable voltage level, neither L nor H. Then I found in schematics that this signal is passed through MAX693 so I made a wire jumper in the socket between pins 12-13 and viola, it boots :)

BTW do I need to recompile ROMWBW when I use different FlashROM chip (EN29F040A) that have different ID or will the FW detect it at runtime and writting will work?

**Comment by skiselev** [comment]
Hi,

As the Bill of Materials suggests, MAX693 can be replaced with a cheaper [ADM693ANZ](https://www.mouser.com/ProductDetail/584-ADM693ANZ). Watchdog is not the only function of this IC. It also provides proper reset signal on power-on, and battery backup for SRAM (and that's why RAM CS signal goes through it). You can get by without the watchdog, and battery backup. But without the proper reset, the operation might be unreliable. So if you decide to omit MAX693/ADM693, you should use some another reset circuit, for example DS1233.

RomWBW itself does not write to the Flash ROM, so you don't need to recompile it.
[FLASH4](https://github.com/wwarthen/RomWBW/blob/master/Doc/Contrib/Flash4.txt) tool supports in-system Flash ROM programming. I don't see EN29F040A listed as one of the supported parts. You can try reaching to the author (see link above) and ask him about adding the support. Or better yet, add it yourself - and contribute to the project.

Thanks,
Sergey

**Comment by xrayer** [comment]
Yes, I understand function of the WD also for reset circuit and SRAM bkup, but for now I can simply use reset push-button and have it powere by adapter. I should have some other spare supervisor/reset circuit... ADM693 looks better but currently sold out in local part supplier and for Mouser I'll wait to collect bigger BOM for the shipping. I also had problem with getting square oscillator, I used SMD part soldered on SO8 socket...

I think it would be just good idea to write a line about the needed jumper when WD not used in readme.md for other builders...

I'll have a look on ROMWBW, need to study a bit how to compile, what tool chains I need to install, etc...

BTW at boot it displays CPU clock 10MHz - seems to be hardcoded as I have CPU at 4MHz only. Does it use CPU freq. value for some internal timing code? As I have SIO on it's own 1,8xMHz oscillator console works normally.

**Comment by xlentelectronics** [comment]
Hi, 
I am going to build the easy_z80. 
I want to use a MAX691 instead of a MAX693. Does that give any issues or does that just works fine?

I cannot find in the documentatiopn what the adjustment procedure of RV1 is.
Can you tell me how to adjust RV1?
